[package]
name = "ls-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19.0"
crossterm = "0.26.1"
clap = { version = "4.1.9", features = ["derive"] }
byte-unit = "4.0.19"
unix_permissions_ext = "0.1.2"
users = "0.11.0"